services:
  docchain:
    image: mcr.microsoft.com/devcontainers/go:1-1.24-bookworm
    container_name: docchain_dev
    working_dir: /go/src/docchain
    volumes:
      - ./:/go/src/docchain
      - ./.docker/go/bin:/go/bin
      - ./.docker/go/pkg:/go/pkg
      - ./data:/go/src/docchain/data
    environment:
      - TZ=America/Belem
      - DB_PATH=/go/src/docchain/data/docchain.db
    ports:
      - 8080:8080
    tty: true
    restart: on-failure

  # tsa:
  #   image: freetsa/tsa:latest
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - ./tsa-data:/var/lib/tsa
  #   environment:
  #     - TSA_URL=http://localhost:8081
  #   restart: unless-stopped
